### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by SeeLook** [dhabyx/plasma-simpleMonitor#12]
Privet :-)
Thanks for the plasmoid. It is the best system monitor ever - only conky can compete... Network stats appreciated...

Here is Polish translation:
https://github.com/SeeLook/plasma-simpleMonitor

I forked the project but I couldn't find how to send it back to You.

**Comment by KonstantinShtepa** [comment]
Hello. Thanks for your help! )
Did you test changes?

**Comment by SeeLook** [comment]
No...
I couldn't. Translation is not loaded even if it is installed in system wide proper place.
Any clue?

**Comment by KonstantinShtepa** [comment]
Did you install plasmoid using cmake as mention in installation guide? Or maybe Polish is not set as your main language in system? If nether of these two then I don't know.

**Comment by SeeLook** [comment]
Yes, I installed using cmake, I saw messages that either Polish and Russian translations landed in:
/usr/share/locale/pl/LC_MESSAGES/plasma_applet_org.kde.simpleMonitor.mo apparently.
and I have set Polsih lang as well. I.e. Gmail plasmoid I have translated.
But don't worry, I will investigate it in spare time, so I will let You know if I will find any solution.

**Comment by KonstantinShtepa** [comment]
I updated translation guide. I think that after translated ".po" file you forget to run "./Messages.sh" so it would update your ".mo" file. Sorry, if older version of translation guide misled you. =)

**Comment by SeeLook** [comment]
Thanks for clue, now it works, but I had to restart sddm.
Finally I could see it (Do not translated texts break the layout) - but looks fine
![screenshot_20170405_101730](https://cloud.githubusercontent.com/assets/945374/24696504/fcd51bb2-19e9-11e7-872f-a7c86e942b2a.png)
![screenshot_20170405_102013](https://cloud.githubusercontent.com/assets/945374/24696513/03128f5a-19ea-11e7-96c1-8082e63a26fa.png)

**Comment by KonstantinShtepa** [comment]
Looks good to me.

**Comment by KonstantinShtepa** [comment]
You can send a merge request by clicking on button "New pull request" in dhabyx/plasma-simpleMonitor repository([GitHub Help: Creating a pull request](https://help.github.com/articles/creating-a-pull-request/)) or you can tell me when you commit changes to your repository so I can pick these changes from your repository.
