### ISSUE TITLE
How install in KDE4?

### ISSUE THREAD

**Issue by RastaDill** [dhabyx/plasma-simpleMonitor#19]
Hello. How right install this plasmoid in KDE4 with localisation?
Way install with cmake, i guess, suitable for Plasma 5, not for KDE4.

P.S.: Description install with cmake have wrong.
source: -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ../
need: -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ../../
otherwise: CMake Error: The source directory "/home/user/Git/GitHub/plasma-simpleMonitor/plasmoid" does not appear to contain CMakeLists.txt.

**Comment by KonstantinShtepa** [comment]
New plasmoid is only KDE5(Plasma2). And old one(for kde4) doesn't have translation and deprecated.

About install description - you are right. I would fix it. There should be `cd plasma-simpleMonitor`.

**Comment by dhabyx** [comment]
@RastaDill you can use kde4 branch with legacy code
