### ISSUE TITLE
Use Plasma components where available

### ISSUE THREAD

**Issue by lbeltrame** [dhabyx/plasma-simpleMonitor#4]
It would be nice to have stuff like `Label` from Plasma components instead of `Text` because like this you can get rid of _all_ hardcoded colors, and have the plasmoid follow the theme's colors.

**Comment by KonstantinShtepa** [comment]
I don't think that it's such a good idea. Theme-colors good for standard text-based plasmoid. It wouldn't be good for graphical plasmoid such as this. Instead there should be choice of internal color themes in plasmoid so user can choice what he likes and what behaves better with current user desktop theme.
