### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by madurani** [dhabyx/plasma-simpleMonitor#55]
After last update of plasma-kde all sensors from widget are lost. I tried delete mentioned widget and install from package and compile from source, but problem persist:
![image](https://user-images.githubusercontent.com/49711883/122216925-3643a900-cead-11eb-8d13-fd201bf18aa7.png)
Before update of kde widget worked properly.

**Comment by TakoTakoo** [comment]
@madurani 
https://github.com/dfaust/plasma-applet-netspeed-widget/issues/28#issuecomment-863841712

**Comment by Djeremaille** [comment]
Same issue. Even with ksysguard installed.

**Comment by madurani** [comment]
After installation of package ksysguard simpleMonitoragain work properly.Thanks.

![image](https://user-images.githubusercontent.com/49711883/122735052-f6027300-d27e-11eb-8512-6b1fd24df669.png)
