### ISSUE TITLE
After recent update one cpu is showing 100% utilisation but it is false display

### ISSUE THREAD

**Issue by mcloaked** [dhabyx/plasma-simpleMonitor#61]
After updating my systems in the past few days on Arch Linux, the plasma desktop widget 'Simple Monitor' that has always shown the cpu utilisation normally on all cores, has started showing one of the cpus pegged at 100% utilization (it is cpu 3 on a laptop with 8 cpus threaded, and cpu 4 on a desktop which has 16 cpus threaded, and both are different hardware with one being Intel and the other AMD Ryzen). On the other hand temperatures are normal, and htop shows all cpus operating at low cpu percentages ( <4%).  So it seems that a recent update to the plasma desktop presumably has led to a faulty Simple Monitor widget that is displaying anomalous utilization on one core, even though that core is actually running at low utilization?  Is it possible that the widget can be updated?

I am running latest Linux kernel 6.4.4, with plasma-desktop 5.27.6-1, and kde-system-meta 23.04-1

**Comment by mcloaked** [comment]
I downgraded the kernel back to 6.4.3 and the issue is no longer present - so it is clearly a bug in kernel 6.4.4 so it is not an issue for Simple Monitor. I will close this issue.

**Comment by mcloaked** [comment]
Closing

**Comment by mcloaked** [comment]
This issue is the subject of kernel bug reports and LKML mail. 
https://bugzilla.kernel.org/show_bug.cgi?id=217699
https://bugzilla.kernel.org/show_bug.cgi?id=217700
https://lore.kernel.org/lkml/12251678.O9o76ZdvQC@natalenko.name/

In the LKML thread Jens Axboe has said that the iowait at 100% is not indicative of the core running at 100% utilisation, and that it is the userspace tool, in this case the Simple Monitor widget that is incorrectly displaying the core utilisation, and should not show 100% when the iowait is at 100%. Therefore the widget needs to be fixed as this is now classified as a bug in Simple Monitor.

**Comment by Fijxu** [comment]
This is related too, I opened it like 3 days ago: https://bbs.archlinux.org/viewtopic.php?id=287343

**Comment by mcloaked** [comment]
Also https://bbs.archlinux.org/viewtopic.php?pid=2111438#p2111438

**Comment by mcloaked** [comment]
Tested kernel 6.4.6 built with the referenced patch  [1] , from the kernel bugzilla, and the anomalous 100% cpu activity on a single core is no longer displayed in the System Monitor widget, and mpstat no longer shows >94% io-wait. So this resolves the issue for my systems.

[1] https://lore.kernel.org/lkml/11ded843-ac08-2306-ad0f-586978d038b1@kernel.dk/raw

So this no longer needs any change to the System Monitor widget, and I will close this issue.
