### ISSUE TITLE
Before 0.6

### ISSUE THREAD

**Issue by KonstantinShtepa** [dhabyx/plasma-simpleMonitor#7]
Plasmoid almost ready to release.
Questions to do before release:

How column with distroInfo(icon and text info) should behaive? 
- Should icon be resized to fit text.width if it's more that 10px? If yes, is there a need for distro icon migration from 100px png files to svg for better scaling? 
- Should limit to maximumwidth of column() set to max(icon.width or 100px, text.width) - should column.width became static?

**Comment by dhabyx** [comment]
Fit the icon to the text size can be problematic, if the name is too small the icon should be smallest or big in oposite case; and the layout can will be break.

Maybe the best solution for this is make a new design with a more modular layout, and can be think for this for new realease with new components.

In my opinnion, the maximounWidth is the best solution for now, and we can use another branch for the newest version with a best solution for this problem.

**Comment by KonstantinShtepa** [comment]
Sorry, there's typo. Not 10px, but 100px. I think maybe it's better to resize icon accordingly to icon.width = max(100, text.width) so on systems with big text(text.width > 100) icon would be bigger.

As I understand you are agree with other question - about settings distroInfo column maximumWidth to minimumWidth so it wouldn't be resized when plasmoid size changes?

**Comment by dhabyx** [comment]
I agree with resize icon according to your suggestion.

About the distroInfo column, in some cases its possible that the distro icon can take big sizes, but maybe only we have test this situations and see the plasmoid behavioral

**Comment by KonstantinShtepa** [comment]
I think I already did what I can before 0.6. So it's need your testing and after that it's ready to launch.
